// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mzxfdllgfznnsgjyesce.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im16eGZkbGxnZnpubnNnanllc2NlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY2NDIzNDYsImV4cCI6MjA2MjIxODM0Nn0.jb8iofMzvuhDMVz8SO2e7RSHb-TWRtAs_duk68dKvAk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});